openapi: 3.0.2
info:
  title: "API"
  version: "1.0.0"
  contact:
    name: Aleksey Radionov
    email: pretorean@gmail.com

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

servers:
  - url: https://localhost:8080/api/v1/auth
    description: Local test server dev3
  - url: https://ownfactory.org/api/v1/auth
    description: Production Server

paths:
  /register:
    summary: User registration
    description: User registration
    post:
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "models.yaml#/components/schemas/RegistrationRequestDto"
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                $ref: "../common/models.yaml#/components/schemas/OtpRequired"
        default:
          $ref: "../common/errors.yaml#/components/responses/ApiErrorResponse"
